vars: {
  d2-config: {
    sketch: true
  }
}

Huawei: {
  style: {
    fill: "#f97c7c"
    border-radius: 5
  }
  api_gw -> ELB
  ELB -> SuperApp_BE
  SuperApp_BE -> GCP
}
GCP: {
  style: {
    fill: "#BEE3BA"
    border-radius: 5
  }
  Kong_GW -> Authen
  Authen -> SuperApp_BE
  SuperApp_BE -> Cloud SQL
}
